---
basic_packages:
  - ffmpeg
  - gnome-tweaks
  - gnome-extensions-app
  - p7zip
  - p7zip-plugins
  - unzip
  - wget
  - curl
  - htop
  - btop
  - fastfetch
  - lm_sensors
  - nvtop
  - libva-utils

laptop_packages:
  - switcheroo-control
  - upower
  - powertop
  - tuned
  - tuned-ppd
  - mokutil

network_packages:
  - tailscale

nvidia_packages:
  - kernel-devel-matched
  - akmod-nvidia
  - xorg-x11-drv-nvidia-cuda
  - xorg-x11-drv-nvidia-power
  - nvidia-settings
  - libva-nvidia-driver
  - vulkan-tools

multimedia_packages:
  - gstreamer1-libav
  - gstreamer1-plugin-openh264
  - gstreamer1-plugins-bad-free
  - gstreamer1-plugins-bad-freeworld
  - gstreamer1-plugins-ugly
  - mesa-va-drivers-freeworld

gaming_packages:
  - steam

dev_tools:
  - code
  - git
  - gh
  - rustup
  - nodejs
  - npm
  - python3-pip
  - pipx
  - fuse

jetbrains_toolbox_release_api_url: "https://data.services.jetbrains.com/products/releases?code=TBA&latest=true&type=release"
jetbrains_toolbox_install_dir: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/share/JetBrains/Toolbox"
jetbrains_toolbox_bin_dir: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/bin"
jetbrains_toolbox_archive_path: "/tmp/jetbrains-toolbox.tar.gz"

tauri_development_enabled: false

tauri_development_packages:
  - webkit2gtk4.1-devel
  - webkitgtk6.0-devel
  - javascriptcoregtk4.1-devel
  - openssl-devel
  - gtk3-devel
  - libsoup3-devel
  - libappindicator-gtk3-devel
  - librsvg2-devel
  - libxdo-devel
  - pkgconf-pkg-config
  - file

flatpaks:
  - md.obsidian.Obsidian
  - com.spotify.Client
  - io.github.zen_browser.zen
  - org.telegram.desktop
  - com.github.johnfactotum.Foliate
  - com.mattjakeman.ExtensionManager
  - net.davidotek.pupgui2

unwanted_jetbrains_flatpaks:
  - com.jetbrains.RustRover
  - com.jetbrains.IntelliJ-IDEA-Ultimate

unwanted_steam_flatpaks:
  - com.valvesoftware.Steam

unwanted_packages:
  - rhythmbox

validation_rpm_packages:
  - tailscale
  - akmod-nvidia
  - xorg-x11-drv-nvidia-cuda
  - libva-nvidia-driver
  - tuned-ppd
  - switcheroo-control
  - code
  - gh
  - steam

validation_flatpaks:
  - io.github.zen_browser.zen
