- name: Fedora Workstation Setup
  hosts: local
  become: True
  vars_files:
    - defaults.yaml
  tasks:
  - name: install all updates
    become: True
    tags:
      - update
      - upgrade
    ansible.builtin.dnf:
      name: '*'
      update_cache: yes
      state: latest

  - name: Fedora workstation repositories
    become: True
    tags:
      - always
    ansible.builtin.dnf:
      name:
        - fedora-workstation-repositories
        - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
        - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
      state: present
      disable_gpg_check: yes

  - name: Install basic packages
    become: True
    tags:
      - basic
    ansible.builtin.dnf:
      name: "{{ basic_packages }}"
      state: present
      allowerasing: True

  - name: Install Dev and Ops tools
    become: True
    tags:
      - dev
    block:
      - name: Add VS Code repository
        ansible.builtin.yum_repository:
          name: vscode
          description: Visual Studio Code
          baseurl: https://packages.microsoft.com/yumrepos/vscode
          gpgkey: https://packages.microsoft.com/keys/microsoft.asc
          gpgcheck: True
      - name: Add GitHub CLI repository
        ansible.builtin.yum_repository:
          name: github-cli
          description: GitHub CLI
          baseurl: https://cli.github.com/packages/rpm/
          gpgkey: https://cli.github.com/packages/rpm/gh-cli.repo
          gpgcheck: True
      - name: Install Dev and Ops packages
        ansible.builtin.dnf:
          name: "{{ dev_tools }}"
          state: present

  - name: Remove unwanted Packages
    become: True
    tags:
      - unwanted
      - uninstall
      - remove
    ansible.builtin.dnf:
      name: "{{ unwanted_packages }}"
      state: absent

  - name: Install Flatpaks
    become: False
    tags:
      - flatpak
    block:
      - name: Add the flathub flatpak repository remote to the user installation
        community.general.flatpak_remote:
          name: flathub
          state: present
          flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
          method: user

      - name: Install multiple packages
        community.general.flatpak:
          name: "{{ flatpaks }}"
          remote: "flathub"
          method: "user"
